### ISSUE TITLE
Include CONTRIBUTING and CODE_OF_CONDUCT files

### ISSUE THREAD

**Issue by bypratyush** [angulardevelopment/multi-step-form#1]
I'd like to update the repository with the CONTRIBUTING file and the CODE_OF_CONDUCT file so that everyone can have a clear idea of creating forks and contributing effortlessly.

Can you please assign this task to me?

**Comment by sunny7899** [comment]
Go ahead @pratyush090506

**Comment by Sandigupta** [comment]
@sunny7899 Assign this to me.

**Comment by sunny7899** [comment]
Go ahead @Sandigupta

**Comment by Sandigupta** [comment]
@sunny7899 thanks

**Comment by Arshadkh123** [comment]
hey @sunny7899 I would also like to work on this please assign me this to me.

**Comment by sunny7899** [comment]
Go ahead @Arshadkh123

**Comment by bypratyush** [comment]
@sunny7899 Added the PR for this issue. Kindly review it.
